version: "3.8"
services:
    fires.node:
      build:
        context: .
        dockerfile: ./docker/node.Dockerfile
      working_dir: /app
      env_file: .env
      volumes:
        - ./:/app
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
      command: sh -c "npm install && npm run generate && npm run start"
      restart: always
      networks:
        - reverse-proxy
        - default
      expose:
        - "${EXPOSE_PORT}"
      environment:
        HOST: "0.0.0.0"
        PORT: "3000"
        VIRTUAL_HOST: "${VIRTUAL_HOST}"
    fires.nginx:
      build:
        context: .
        dockerfile: ./docker/nginx.Dockerfile
      restart: always
      env_file: .env
      environment:
        VIRTUAL_HOST: "${VIRTUAL_HOST}"
      networks:
        - reverse-proxy
        - default
      volumes:
        - ./public:/app/public:ro
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
      depends_on:
        - fires.node
networks:
  reverse-proxy:
    external: true
